
import javax.swing.JOptionPane;


public class Menu extends javax.swing.JFrame {
int matrizNumeros [][];
int filas=0,columnas=0;
    
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        imprimirMatriz = new javax.swing.JButton();
        llenarMatriz = new javax.swing.JButton();
        buscarPares = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 36)); // NOI18N
        jLabel1.setText("Matrices en Java ");

        imprimirMatriz.setText("IMPRIMIR MATRIZ ");
        imprimirMatriz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimirMatrizActionPerformed(evt);
            }
        });

        llenarMatriz.setText("LLENAR MATRIZ");
        llenarMatriz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                llenarMatrizActionPerformed(evt);
            }
        });

        buscarPares.setText("BUSCAR PARES");
        buscarPares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarParesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(llenarMatriz)
                        .addGap(35, 35, 35)
                        .addComponent(imprimirMatriz)
                        .addGap(56, 56, 56)
                        .addComponent(buscarPares)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imprimirMatriz)
                    .addComponent(llenarMatriz)
                    .addComponent(buscarPares))
                .addContainerGap(361, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void llenarMatrizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_llenarMatrizActionPerformed
     filas=Integer.parseInt(JOptionPane.showInputDialog(null,"Valor Numero de Filas:"));
     columnas=Integer.parseInt(JOptionPane.showInputDialog(null,"Valor Numero de Columnas:"));
     matrizNumeros=new int [filas][columnas];
     for(int i=0;i<filas;i++){
         for(int j=0;j<columnas;j++){
             matrizNumeros[i][j]=Integer.parseInt(JOptionPane.showInputDialog(null,"Valor para la posicion:"+i+","+j));
         }
     }
     JOptionPane.showMessageDialog(rootPane, "La matriz esta llena");
    }//GEN-LAST:event_llenarMatrizActionPerformed

    private void imprimirMatrizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimirMatrizActionPerformed
       for(int i=0;i<filas;i++){
           for(int j=0;j<columnas;j++){
                JOptionPane.showMessageDialog(rootPane,"Numero Matriz, Posicion "+i+","+j+" = "+matrizNumeros[i][j]);
           }
       }
    }//GEN-LAST:event_imprimirMatrizActionPerformed

    private void buscarParesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarParesActionPerformed
       for(int i=0;i<filas;i++){
           for(int j=0;j<columnas;j++){
               if(matrizNumeros[i][j]%2==0){
                JOptionPane.showMessageDialog(rootPane,"En la Posicion "+i+","+j+",hay un numero PAR,el numero es:"+matrizNumeros[i][j]);
           }}
       }
    }//GEN-LAST:event_buscarParesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarPares;
    private javax.swing.JButton imprimirMatriz;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton llenarMatriz;
    // End of variables declaration//GEN-END:variables
}
