
import javax.swing.JOptionPane;


public class Votaciones extends javax.swing.JFrame {
  int cantidadCandidatoss;
   int cantidadMesasInstaladas;
   int matrizCantidadMesas[][];
   int sumaMesas[];
   int mayor=0;
   Candidato listaCandidatos[];
    public Votaciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        mesasInstaladas = new javax.swing.JButton();
        cantidadCandidatos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        candidatoGanador = new javax.swing.JButton();
        mesaMasVotada = new javax.swing.JButton();
        mesaMenosVotada = new javax.swing.JButton();
        promedioVotos = new javax.swing.JButton();
        totalVotos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 24)); // NOI18N
        jLabel1.setText("Resultados");

        mesasInstaladas.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        mesasInstaladas.setText("Mesas Instaladas");
        mesasInstaladas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesasInstaladasActionPerformed(evt);
            }
        });

        cantidadCandidatos.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        cantidadCandidatos.setText("Cantidad Candidatos");
        cantidadCandidatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadCandidatosActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 24)); // NOI18N
        jLabel2.setText("Puesto de Votación");

        candidatoGanador.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        candidatoGanador.setText("Candidato Ganador");
        candidatoGanador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                candidatoGanadorActionPerformed(evt);
            }
        });

        mesaMasVotada.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        mesaMasVotada.setText("Mesa mas Votada");
        mesaMasVotada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesaMasVotadaActionPerformed(evt);
            }
        });

        mesaMenosVotada.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        mesaMenosVotada.setText("Mesa Menos Votada");
        mesaMenosVotada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesaMenosVotadaActionPerformed(evt);
            }
        });

        promedioVotos.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        promedioVotos.setText("Promedio Votos por mesa");
        promedioVotos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                promedioVotosActionPerformed(evt);
            }
        });

        totalVotos.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        totalVotos.setText("Total de votos");
        totalVotos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalVotosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(cantidadCandidatos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mesasInstaladas)
                .addGap(140, 140, 140))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(promedioVotos)
                                .addGap(64, 64, 64)
                                .addComponent(totalVotos)
                                .addGap(107, 107, 107))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(candidatoGanador)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(mesaMasVotada)
                                .addGap(52, 52, 52)
                                .addComponent(mesaMenosVotada))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(jLabel1)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mesasInstaladas)
                    .addComponent(cantidadCandidatos))
                .addGap(58, 58, 58)
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(candidatoGanador)
                    .addComponent(mesaMasVotada)
                    .addComponent(mesaMenosVotada))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(promedioVotos)
                    .addComponent(totalVotos))
                .addContainerGap(125, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cantidadCandidatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadCandidatosActionPerformed
        cantidadCandidatoss=Integer.parseInt( JOptionPane.showInputDialog("¿Cual es la cantidad de candidatos?"));
         listaCandidatos=new Candidato[cantidadCandidatoss];
         for(int i=0;i<listaCandidatos.length;i++){
             listaCandidatos[i]=new Candidato(JOptionPane.showInputDialog("Nombre del candidato:"+(i+1)),(Integer.parseInt( JOptionPane.showInputDialog("Numero del Candidato:"+(i+1)))));
         }  
    }//GEN-LAST:event_cantidadCandidatosActionPerformed

    private void mesasInstaladasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesasInstaladasActionPerformed
       if(cantidadCandidatoss==0){
           JOptionPane.showMessageDialog(rootPane,"NUMERO DE CANDIDATOS NO REGISTRADO");
       }else{
        cantidadMesasInstaladas=Integer.parseInt( JOptionPane.showInputDialog("¿Cual es la cantidad de mesas instaladas?"));
       matrizCantidadMesas=new int [cantidadCandidatoss][cantidadMesasInstaladas];
       for(int i=0;i<cantidadCandidatoss;i++){
           for(int j=0;j<cantidadMesasInstaladas;j++){
               matrizCantidadMesas[i][j]=Integer.parseInt( JOptionPane.showInputDialog("Cantidad de votos,Candidato:"+(i+1)+",Mesa:"+(j+1)));
           }
       }}
       
    }//GEN-LAST:event_mesasInstaladasActionPerformed

    private void candidatoGanadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_candidatoGanadorActionPerformed
       int suma[]=new int [cantidadCandidatoss];
        for(int i=0;i<cantidadCandidatoss;i++){
           for(int j=0;j<cantidadMesasInstaladas;j++){
            suma[i]+=matrizCantidadMesas[i][j];
           }
       }
         mayor=0;
       int contadorCandidatoConMasVotos=0;
        for(int i=0;i<suma.length;i++){
           if(suma[i]>mayor){
               mayor=suma[i];
              contadorCandidatoConMasVotos=i;
           }}
        JOptionPane.showMessageDialog(rootPane,"Candidato Ganador: "+listaCandidatos[contadorCandidatoConMasVotos]+" ,Cantidad de Votos:"+mayor);
            
    }//GEN-LAST:event_candidatoGanadorActionPerformed

    private void mesaMasVotadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesaMasVotadaActionPerformed
        sumaMesas=new int [cantidadMesasInstaladas];
        for(int j=0;j<cantidadMesasInstaladas;j++){
         for(int i=0;i<cantidadCandidatoss;i++){
            sumaMesas[j]+=matrizCantidadMesas[i][j];
           }
       }
       int contadorMayor=0;
        for(int i=0;i<sumaMesas.length;i++){
           if(sumaMesas[i]>mayor){
               mayor=sumaMesas[i];
               contadorMayor=i;
           }
       }
        JOptionPane.showMessageDialog(rootPane,"Mesa con mayor votos: "+(contadorMayor+1)+" ,Cantidad de Votos:"+mayor);
       
       
    }//GEN-LAST:event_mesaMasVotadaActionPerformed

    private void mesaMenosVotadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesaMenosVotadaActionPerformed

        int menor=mayor;
       int contadorMenor=0;
        for(int i=0;i<sumaMesas.length;i++){
           if(sumaMesas[i]<menor){
               menor=sumaMesas[i];
               contadorMenor=i;
           }
       }
        JOptionPane.showMessageDialog(rootPane,"Mesa con menor votos: "+(contadorMenor+1)+" ,Cantidad de Votos:"+menor);
    }//GEN-LAST:event_mesaMenosVotadaActionPerformed

    private void promedioVotosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_promedioVotosActionPerformed
       float promedioVotosPorMesa[]=new float[cantidadMesasInstaladas];
       for(int i=0;i<promedioVotosPorMesa.length;i++){
           promedioVotosPorMesa[i]=sumaMesas[i]/cantidadMesasInstaladas;
           JOptionPane.showMessageDialog(rootPane,"Promedio Mesa: "+(i+1)+","+promedioVotosPorMesa[i]);
       }
    }//GEN-LAST:event_promedioVotosActionPerformed

    private void totalVotosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalVotosActionPerformed
        int totalVotos=0;
        for(int i=0;i<cantidadCandidatoss;i++){
           for(int j=0;j<cantidadMesasInstaladas;j++){
              totalVotos=totalVotos+matrizCantidadMesas[i][j];
           }
       }
        JOptionPane.showMessageDialog(rootPane,"Total de votos Punto de Votacion: "+totalVotos);
    }//GEN-LAST:event_totalVotosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Votaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Votaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Votaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Votaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Votaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton candidatoGanador;
    private javax.swing.JButton cantidadCandidatos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton mesaMasVotada;
    private javax.swing.JButton mesaMenosVotada;
    private javax.swing.JButton mesasInstaladas;
    private javax.swing.JButton promedioVotos;
    private javax.swing.JButton totalVotos;
    // End of variables declaration//GEN-END:variables
}
